-- Inserindo Dados na Tabela GENEROS:
INSERT INTO GENEROS (NOME) VALUES
('Ação'),
('Aventura'),
('Comédia'),
('Drama'),
('Fantasia'),
('Ficção Científica'),
('Super-herói');

-- Inserindo Dados na Tabela CATEGORIAS:
INSERT INTO CATEGORIAS (NOME, VALOR) VALUES
('Lançamento', 5.00),
('Padrão', 2.50),
('Clássico', 1.00);

-- Inserindo Dados na Tabela FILMES:
INSERT INTO FILMES (TITULO_ORIGINAL, TITULO, QUANTIDADE, FK_CATEGORIA, FK_GENERO) VALUES
('Homem de Ferro', 'Homem de Ferro', 5, (SELECT COD_CAT FROM CATEGORIAS WHERE NOME = 'Lançamento'), (SELECT COD_GEN FROM GENEROS WHERE NOME = 'Ação')),
('O Incrível Hulk', 'O Incrível Hulk', 3, (SELECT COD_CAT FROM CATEGORIAS WHERE NOME = 'Lançamento'), (SELECT COD_GEN FROM GENEROS WHERE NOME = 'Ação')),
('Homem de Ferro 2', 'Homem de Ferro 2', 4, (SELECT COD_CAT FROM CATEGORIAS WHERE NOME = 'Lançamento'), (SELECT COD_GEN FROM GENEROS WHERE NOME = 'Ação')),
('Thor', 'Thor', 4, (SELECT COD_CAT FROM CATEGORIAS WHERE NOME = 'Lançamento'), (SELECT COD_GEN FROM GENEROS WHERE NOME = 'Ação')),
('Capitão América: O Primeiro Vingador', 'Capitão América: O Primeiro Vingador', 4, (SELECT COD_CAT FROM CATEGORIAS WHERE NOME = 'Lançamento'), (SELECT COD_GEN FROM GENEROS WHERE NOME = 'Ação')),
('Os Vingadores', 'Os Vingadores', 6, (SELECT COD_CAT FROM CATEGORIAS WHERE NOME = 'Padrão'), (SELECT COD_GEN FROM GENEROS WHERE NOME = 'Fantasia')),
('Homem de Ferro 3', 'Homem de Ferro 3', 4, (SELECT COD_CAT FROM CATEGORIAS WHERE NOME = 'Padrão'), (SELECT COD_GEN FROM GENEROS WHERE NOME = 'Fantasia')),
('Thor: O Mundo Sombrio', 'Thor: O Mundo Sombrio', 3, (SELECT COD_CAT FROM CATEGORIAS WHERE NOME = 'Padrão'), (SELECT COD_GEN FROM GENEROS WHERE NOME = 'Fantasia')),
('Capitão América: O Soldado Invernal', 'Capitão América: O Soldado Invernal', 4, (SELECT COD_CAT FROM CATEGORIAS WHERE NOME = 'Clássico'), (SELECT COD_GEN FROM GENEROS WHERE NOME = 'Ficção Científica')),
('Guardiões da Galáxia', 'Guardiões da Galáxia', 5, (SELECT COD_CAT FROM CATEGORIAS WHERE NOME = 'Clássico'), (SELECT COD_GEN FROM GENEROS WHERE NOME = 'Ficção Científica')),
('Vingadores: Era de Ultron', 'Vingadores: Era de Ultron', 6, (SELECT COD_CAT FROM CATEGORIAS WHERE NOME = 'Clássico'), (SELECT COD_GEN FROM GENEROS WHERE NOME = 'Ficção Científica')),
('Homem-Formiga', 'Homem-Formiga', 3, (SELECT COD_CAT FROM CATEGORIAS WHERE NOME = 'Clássico'), (SELECT COD_GEN FROM GENEROS WHERE NOME = 'Ficção Científica')),
('Capitão América: Guerra Civil', 'Capitão América: Guerra Civil', 5, (SELECT COD_CAT FROM CATEGORIAS WHERE NOME = 'Lançamento'), (SELECT COD_GEN FROM GENEROS WHERE NOME = 'Ação')),
('Doutor Estranho', 'Doutor Estranho', 4, (SELECT COD_CAT FROM CATEGORIAS WHERE NOME = 'Lançamento'), (SELECT COD_GEN FROM GENEROS WHERE NOME = 'Ação')),
('Guardiões da Galáxia Vol. 2', 'Guardiões da Galáxia Vol. 2', 5, (SELECT COD_CAT FROM CATEGORIAS WHERE NOME = 'Lançamento'), (SELECT COD_GEN FROM GENEROS WHERE NOME = 'Ação'));

-- Inserindo Dados na Tabela ATORES:
INSERT INTO ATORES (NOME) VALUES
('Robert Downey Jr.'),
('Chris Evans'),
('Chris Hemsworth'),
('Mark Ruffalo'),
('Scarlett Johansson'),
('Jeremy Renner'),
('Tom Holland'),
('Chadwick Boseman'),
('Benedict Cumberbatch'),
('Paul Rudd'),
('Brie Larson'),
('Chris Pratt'),
('Zoe Saldana'),
('Dave Bautista'),
('Josh Brolin');

-- Inserindo Dados na Tabela FILMES_ATORES:
INSERT INTO FILMES_ATORES (FK_ATOR, FK_FILME, ATOR, DIRETOR) VALUES
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Robert Downey Jr.'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Homem de Ferro'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Mark Ruffalo'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'O Incrível Hulk'), 'Sim', 'Sim'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Robert Downey Jr.'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Homem de Ferro 2'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Chris Hemsworth'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Thor'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Chris Evans'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Capitão América: O Primeiro Vingador'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Robert Downey Jr.'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Os Vingadores'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Mark Ruffalo'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Os Vingadores'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Chris Evans'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Os Vingadores'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Scarlett Johansson'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Os Vingadores'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Jeremy Renner'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Os Vingadores'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Robert Downey Jr.'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Homem de Ferro 3'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Chris Hemsworth'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Thor: O Mundo Sombrio'), 'Sim', 'Sim'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Chris Evans'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Capitão América: O Soldado Invernal'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Chris Pratt'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Guardiões da Galáxia'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Robert Downey Jr.'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Vingadores: Era de Ultron'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Chris Evans'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Vingadores: Era de Ultron'), 'Sim', 'Sim'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Chris Hemsworth'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Vingadores: Era de Ultron'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Mark Ruffalo'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Vingadores: Era de Ultron'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Jeremy Renner'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Vingadores: Era de Ultron'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Benedict Cumberbatch'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Doutor Estranho'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Chris Pratt'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Guardiões da Galáxia Vol. 2'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Zoe Saldana'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Guardiões da Galáxia Vol. 2'), 'Sim', 'Não'),
((SELECT COD_ATOR FROM ATORES WHERE NOME = 'Dave Bautista'), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Guardiões da Galáxia Vol. 2'), 'Sim', 'Não');

-- Inserindo Dados na Tabela ENDERECOS:
INSERT INTO ENDERECOS (LOGRADOURO, TIPO_LOG, COMPLEMENTO, CIDADE, UF, CEP, NUMERO, BAIRRO) VALUES
('Rua das Flores', 'Rua', 'Apto 101', 'São Paulo', 'SP', '01001000', '100', 'Centro'),
('Avenida Paulista', 'Avenida', 'Conj. 200', 'São Paulo', 'SP', '01311200', '2000', 'Bela Vista'),
('Rua Augusta', 'Rua', 'Casa', 'São Paulo', 'SP', '01412100', '300', 'Consolação'),
('Rua da Consolação', 'Rua', 'Apto 202', 'São Paulo', 'SP', '01303000', '400', 'Consolação'),
('Rua Vergueiro', 'Rua', 'Bloco A', 'São Paulo', 'SP', '01504000', '500', 'Liberdade'),
('Avenida Faria Lima', 'Avenida', 'Conj. 300', 'São Paulo', 'SP', '01451001', '6000', 'Itaim Bibi'),
('Rua 25 de Março', 'Rua', 'Loja 10', 'São Paulo', 'SP', '01001010', '700', 'Centro'),
('Avenida Ipiranga', 'Avenida', 'Sala 500', 'São Paulo', 'SP', '01002000', '800', 'República'),
('Rua Oscar Freire', 'Rua', 'Casa', 'São Paulo', 'SP', '01426000', '900', 'Jardins'),
('Rua Haddock Lobo', 'Rua', 'Apto 303', 'São Paulo', 'SP', '01414001', '1000', 'Cerqueira César');

-- Inserindo Dados na Tabela PROFISSOES:
INSERT INTO PROFISSOES (NOME) VALUES
('Engenheiro'),
('Médico'),
('Professor'),
('Advogado'),
('Arquiteto'),
('Programador'),
('Enfermeiro'),
('Farmacêutico'),
('Dentista'),
('Jornalista');

-- Inserindo Dados na Tabela CLIENTES:
INSERT INTO CLIENTES (CPF, NOME, TELEFONE, FK_PROFISSAO) VALUES
('12345678901', 'João Silva', '11987654321', (SELECT COD_PROF FROM PROFISSOES WHERE NOME = 'Engenheiro')),
('23456789012', 'Maria Souza', '11976543210', (SELECT COD_PROF FROM PROFISSOES WHERE NOME = 'Médico')),
('34567890123', 'José Santos', '11965432109', (SELECT COD_PROF FROM PROFISSOES WHERE NOME = 'Professor')),
('45678901234', 'Ana Oliveira', '11954321098', (SELECT COD_PROF FROM PROFISSOES WHERE NOME = 'Advogado')),
('56789012345', 'Carlos Pereira', '11943210987', (SELECT COD_PROF FROM PROFISSOES WHERE NOME = 'Arquiteto')),
('67890123456', 'Paula Lima', '11932109876', (SELECT COD_PROF FROM PROFISSOES WHERE NOME = 'Programador')),
('78901234567', 'Rafael Costa', '11921098765', (SELECT COD_PROF FROM PROFISSOES WHERE NOME = 'Enfermeiro')),
('89012345678', 'Fernanda Alves', '11910987654', (SELECT COD_PROF FROM PROFISSOES WHERE NOME = 'Farmacêutico')),
('90123456789', 'Lucas Rodrigues', '11909876543', (SELECT COD_PROF FROM PROFISSOES WHERE NOME = 'Dentista')),
('01234567890', 'Juliana Fernandes', '11998765432', (SELECT COD_PROF FROM PROFISSOES WHERE NOME = 'Jornalista'));


-- Inserindo Dados na Tabela DEPENDENTES:
INSERT INTO DEPENDENTES (FK_CLIENTE, COD_DEP, PARENTESCO) VALUES
((SELECT COD_CLI FROM CLIENTES WHERE NOME = 'João Silva'), (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Maria Souza'), 'Esposa'),
((SELECT COD_CLI FROM CLIENTES WHERE NOME = 'José Santos'), (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Ana Oliveira'), 'Filho'),
((SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Carlos Pereira'), (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Paula Lima'), 'Filha'),
((SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Rafael Costa'), (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Fernanda Alves'), 'Pai'),
((SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Lucas Rodrigues'), (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Juliana Fernandes'), 'Mãe');

-- Inserindo Dados na Tabela CLIENTES_ENDERECOS:
INSERT INTO CLIENTES_ENDERECOS (FK_ENDERECO, FK_CLIENTE) VALUES
((SELECT COD_END FROM ENDERECOS WHERE LOGRADOURO = 'Rua das Flores' AND NUMERO = '100'), (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'João Silva')),
((SELECT COD_END FROM ENDERECOS WHERE LOGRADOURO = 'Rua das Flores' AND NUMERO = '100'), (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Maria Souza')),
((SELECT COD_END FROM ENDERECOS WHERE LOGRADOURO = 'Rua Augusta' AND NUMERO = '300'), (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'José Santos')),
((SELECT COD_END FROM ENDERECOS WHERE LOGRADOURO = 'Rua Augusta' AND NUMERO = '300'), (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Ana Oliveira')),
((SELECT COD_END FROM ENDERECOS WHERE LOGRADOURO = 'Rua Vergueiro' AND NUMERO = '500'), (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Carlos Pereira')),
((SELECT COD_END FROM ENDERECOS WHERE LOGRADOURO = 'Rua Vergueiro' AND NUMERO = '500'), (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Paula Lima')),
((SELECT COD_END FROM ENDERECOS WHERE LOGRADOURO = 'Rua 25 de Março' AND NUMERO = '700'), (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Rafael Costa')),
((SELECT COD_END FROM ENDERECOS WHERE LOGRADOURO = 'Rua 25 de Março' AND NUMERO = '700'), (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Fernanda Alves')),
((SELECT COD_END FROM ENDERECOS WHERE LOGRADOURO = 'Rua Oscar Freire' AND NUMERO = '900'), (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Lucas Rodrigues')),
((SELECT COD_END FROM ENDERECOS WHERE LOGRADOURO = 'Rua Oscar Freire' AND NUMERO = '900'), (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Juliana Fernandes'));

-- Inserindo Dados na Tabela LOCACOES:
INSERT INTO LOCACOES (DATA_LOC, DESCONTO, MULTA, SUB_TOTAL, FK_CLIENTE) VALUES
('2022-01-01', 5.00, 2.00, 50.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'João Silva')),
('2022-01-05', 0.00, 0.00, 30.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Maria Souza')),
('2022-01-10', 10.00, 0.00, 40.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'José Santos')),
('2022-01-15', 0.00, 5.00, 50.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Ana Oliveira')),
('2022-01-20', 5.00, 0.00, 60.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Carlos Pereira')),
('2022-01-25', 0.00, 2.00, 70.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Paula Lima')),
('2022-02-01', 0.00, 0.00, 80.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Rafael Costa')),
('2022-02-05', 10.00, 0.00, 90.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Fernanda Alves')),
('2022-02-10', 0.00, 5.00, 100.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Lucas Rodrigues')),
('2022-02-15', 0.00, 0.00, 110.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Juliana Fernandes')),
('2022-02-20', 5.00, 2.00, 120.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'João Silva')),
('2022-02-25', 0.00, 0.00, 130.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Maria Souza')),
('2022-03-01', 10.00, 0.00, 140.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'José Santos')),
('2022-03-05', 0.00, 5.00, 150.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Ana Oliveira')),
('2022-03-10', 5.00, 0.00, 160.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Carlos Pereira')),
('2022-03-15', 0.00, 2.00, 170.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Paula Lima')),
('2022-03-20', 0.00, 0.00, 180.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Rafael Costa')),
('2022-03-25', 10.00, 0.00, 190.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Fernanda Alves')),
('2022-04-01', 0.00, 5.00, 200.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Lucas Rodrigues')),
('2022-04-05', 0.00, 0.00, 210.00, (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Juliana Fernandes'));

-- Inserindo Dados na Tabela LOCACOES_FILMES:
INSERT INTO LOCACOES_FILMES (FK_LOCACAO, FK_FILME, VALOR, NUM_DIAS, DATA_DEVOL) VALUES
((SELECT COD_LOC FROM LOCACOES WHERE DATA_LOC = '2022-01-01' AND FK_CLIENTE = (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'João Silva')), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Homem de Ferro'), 10.00, 3, '2022-01-04'),
((SELECT COD_LOC FROM LOCACOES WHERE DATA_LOC = '2022-01-05' AND FK_CLIENTE = (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Maria Souza')), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'O Incrível Hulk'), 15.00, 4, '2022-01-09'),
((SELECT COD_LOC FROM LOCACOES WHERE DATA_LOC = '2022-01-10' AND FK_CLIENTE = (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'José Santos')), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Homem de Ferro 2'), 20.00, 5, '2022-01-15'),
((SELECT COD_LOC FROM LOCACOES WHERE DATA_LOC = '2022-01-15' AND FK_CLIENTE = (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Ana Oliveira')), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Thor'), 25.00, 6, '2022-01-21'),
((SELECT COD_LOC FROM LOCACOES WHERE DATA_LOC = '2022-01-20' AND FK_CLIENTE = (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Carlos Pereira')), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Capitão América: O Primeiro Vingador'), 30.00, 7, '2022-01-27'),
((SELECT COD_LOC FROM LOCACOES WHERE DATA_LOC = '2022-01-25' AND FK_CLIENTE = (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Paula Lima')), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Os Vingadores'), 35.00, 8, '2022-02-02'),
((SELECT COD_LOC FROM LOCACOES WHERE DATA_LOC = '2022-02-01' AND FK_CLIENTE = (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Rafael Costa')), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Homem de Ferro 3'), 40.00, 9, '2022-02-08'),
((SELECT COD_LOC FROM LOCACOES WHERE DATA_LOC = '2022-02-05' AND FK_CLIENTE = (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Fernanda Alves')), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Thor: O Mundo Sombrio'), 45.00, 10, '2022-02-14'),
((SELECT COD_LOC FROM LOCACOES WHERE DATA_LOC = '2022-02-10' AND FK_CLIENTE = (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Lucas Rodrigues')), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Capitão América: O Soldado Invernal'), 50.00, 11, '2022-02-20'),
((SELECT COD_LOC FROM LOCACOES WHERE DATA_LOC = '2022-02-15' AND FK_CLIENTE = (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Juliana Fernandes')), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Guardiões da Galáxia'), 55.00, 12, '2022-02-26'),
((SELECT COD_LOC FROM LOCACOES WHERE DATA_LOC = '2022-02-20' AND FK_CLIENTE = (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'João Silva')), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Homem de Ferro 3'), 60.00, 13, '2022-03-04'),
((SELECT COD_LOC FROM LOCACOES WHERE DATA_LOC = '2022-02-25' AND FK_CLIENTE = (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Maria Souza')), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Thor: O Mundo Sombrio'), 65.00, 14, '2022-03-10'),
((SELECT COD_LOC FROM LOCACOES WHERE DATA_LOC = '2022-03-01' AND FK_CLIENTE = (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'José Santos')), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Capitão América: O Soldado Invernal'), 70.00, 15, '2022-03-16'),
((SELECT COD_LOC FROM LOCACOES WHERE DATA_LOC = '2022-03-05' AND FK_CLIENTE = (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Ana Oliveira')), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Vingadores: Era de Ultron'), 75.00, 16, '2022-03-22'),
((SELECT COD_LOC FROM LOCACOES WHERE DATA_LOC = '2022-03-10' AND FK_CLIENTE = (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Carlos Pereira')), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Homem-Formiga'), 80.00, 17, '2022-03-28'),
((SELECT COD_LOC FROM LOCACOES WHERE DATA_LOC = '2022-03-15' AND FK_CLIENTE = (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Paula Lima')), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Capitão América: Guerra Civil'), 85.00, 18, '2022-04-04'),
((SELECT COD_LOC FROM LOCACOES WHERE DATA_LOC = '2022-03-20' AND FK_CLIENTE = (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Rafael Costa')), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Doutor Estranho'), 90.00, 19, '2022-04-10'),
((SELECT COD_LOC FROM LOCACOES WHERE DATA_LOC = '2022-03-25' AND FK_CLIENTE = (SELECT COD_CLI FROM CLIENTES WHERE NOME = 'Fernanda Alves')), (SELECT COD_FILME FROM FILMES WHERE TITULO = 'Guardiões da Galáxia Vol. 2'), 95.00, 20, '2022-04-15');