-- Criação do Banco de Dados Locação de Filmes:
CREATE DATABASE LocacaoFilme;

-- Criação da Tabela GENEROS:
CREATE TABLE GENEROS 
(
    COD_GEN SERIAL PRIMARY KEY NOT NULL,
    NOME VARCHAR(100)
);

-- Criação da Tabela CATEGORIAS:
CREATE TABLE CATEGORIAS 
(
    COD_CAT SERIAL PRIMARY KEY NOT NULL,
    NOME VARCHAR(100),
    VALOR NUMERIC(15,2)
);

-- Criação da Tabela FILMES:
CREATE TABLE FILMES 
(
    COD_FILME SERIAL PRIMARY KEY NOT NULL,
    TITULO_ORIGINAL VARCHAR(100),
    TITULO VARCHAR(100),
    QUANTIDADE INTEGER,
    FK_CATEGORIA INTEGER,
    FK_GENERO INTEGER,
    FOREIGN KEY (FK_CATEGORIA) REFERENCES CATEGORIAS (COD_CAT),
    FOREIGN KEY (FK_GENERO) REFERENCES GENEROS (COD_GEN)
);

-- Criação da Tabela ATORES:
CREATE TABLE ATORES 
(
    COD_ATOR SERIAL PRIMARY KEY NOT NULL,
    NOME VARCHAR(100)
);

-- Criação da Tabela FILMES_ATORES:
CREATE TABLE FILMES_ATORES 
(
    FK_ATOR INTEGER NOT NULL,
    FK_FILME INTEGER NOT NULL,
	ATOR VARCHAR(100),
    DIRETOR VARCHAR(100),
    PRIMARY KEY (FK_ATOR, FK_FILME),
    FOREIGN KEY (FK_ATOR) REFERENCES ATORES (COD_ATOR),
    FOREIGN KEY (fk_FILME) REFERENCES FILMES (COD_FILME)
);

-- Criação da Tabela ENDERECOS:
CREATE TABLE ENDERECOS 
(
    COD_END SERIAL PRIMARY KEY NOT NULL,
    LOGRADOURO VARCHAR(40),
    TIPO_LOG VARCHAR(40),
    COMPLEMENTO VARCHAR(20),
    CIDADE VARCHAR(60),
    UF VARCHAR(2),
    CEP VARCHAR(8),
    NUMERO VARCHAR(10),
    BAIRRO VARCHAR(100)
);

-- Criação da Tabela PROFISSÕES:
CREATE TABLE PROFISSOES 
(
    COD_PROF SERIAL PRIMARY KEY NOT NULL,
    NOME VARCHAR(100)
);

-- Criação da Tabela CLIENTES:
CREATE TABLE CLIENTES 
(
    COD_CLI SERIAL PRIMARY KEY NOT NULL,
    CPF VARCHAR(12),
    NOME VARCHAR(100),
    TELEFONE VARCHAR(11),
    FK_PROFISSAO INTEGER,
	FOREIGN KEY (FK_PROFISSAO) REFERENCES PROFISSOES (COD_PROF)
);

-- Criação da Tabela DEPENDENTES:
CREATE TABLE DEPENDENTES 
(
    FK_CLIENTE INTEGER,
    COD_DEP INTEGER,
    PARENTESCO VARCHAR(50),
    PRIMARY KEY (FK_CLIENTE, COD_DEP),
    FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTES (COD_CLI),
	FOREIGN KEY (COD_DEP) REFERENCES CLIENTES (COD_CLI)
);

-- Criação da Tabela CLIENTES_ENDERECOS:
CREATE TABLE CLIENTES_ENDERECOS 
(
    FK_ENDERECO INTEGER,
    FK_CLIENTE INTEGER,
    PRIMARY KEY (FK_ENDERECO, FK_CLIENTE),
    FOREIGN KEY (FK_ENDERECO) REFERENCES ENDERECOS (COD_END),
    FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTES (COD_CLI)
);

-- Criação da Tabela LOCACOES:
CREATE TABLE LOCACOES 
(
    COD_LOC SERIAL PRIMARY KEY NOT NULL,
    DATA_LOC DATE,
    DESCONTO NUMERIC(15,2),
    MULTA NUMERIC(15,2),
    SUB_TOTAL NUMERIC(15,2),
    FK_CLIENTE INTEGER,
    FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTES (COD_CLI)
);

-- Criação da Tabela LOCACOES_FILMES:
CREATE TABLE LOCACOES_FILMES 
(
    FK_LOCACAO INTEGER,
    FK_FILME INTEGER,
    VALOR NUMERIC(15,2),
    NUM_DIAS INTEGER,
    DATA_DEVOL DATE,
    PRIMARY KEY (FK_LOCACAO, FK_FILME),
    FOREIGN KEY (FK_LOCACAO) REFERENCES LOCACOES (COD_LOC),
    FOREIGN KEY (FK_FILME) REFERENCES FILMES (COD_FILME)
);
